"""Add user history table

Revision ID: 099a4f65c6f3
Revises: a008fe75f94e
Create Date: 2025-08-21 12:21:43.117342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099a4f65c6f3'
down_revision: Union[str, Sequence[str], None] = 'a008fe75f94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('changed_fields', sa.JSON(), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_history_action', 'user_history', ['action'], unique=False)
    op.create_index('idx_user_history_changed_by', 'user_history', ['changed_by'], unique=False)
    op.create_index('idx_user_history_created_at', 'user_history', ['created_at'], unique=False)
    op.create_index('idx_user_history_user_id', 'user_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_history_action'), 'user_history', ['action'], unique=False)
    op.create_index(op.f('ix_user_history_changed_by'), 'user_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_user_history_user_id'), 'user_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_history_user_id'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_changed_by'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_action'), table_name='user_history')
    op.drop_index('idx_user_history_user_id', table_name='user_history')
    op.drop_index('idx_user_history_created_at', table_name='user_history')
    op.drop_index('idx_user_history_changed_by', table_name='user_history')
    op.drop_index('idx_user_history_action', table_name='user_history')
    op.drop_table('user_history')
    # ### end Alembic commands ###
