"""Add user management fields and history table

Revision ID: a008fe75f94e
Revises: 2ba896dddd29
Create Date: 2025-08-21 12:20:40.617670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a008fe75f94e'
down_revision: Union[str, Sequence[str], None] = '2ba896dddd29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_check')
    op.alter_column('assignment_history', 'changed_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_assignment_history_action'), 'assignment_history', ['action'], unique=False)
    op.create_index(op.f('ix_assignment_history_assignment_id'), 'assignment_history', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_history_changed_at'), 'assignment_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_assignments_project_id'), 'assignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_index(op.f('ix_assignments_user_id'), 'assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_client_contacts_client_id'), 'client_contacts', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_contacts_email'), 'client_contacts', ['email'], unique=False)
    op.drop_constraint('client_contacts_ibfk_1', 'client_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'client_contacts', 'clients', ['client_id'], ['id'])
    op.alter_column('client_history', 'changed_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_client_history_action'), 'client_history', ['action'], unique=False)
    op.create_index(op.f('ix_client_history_changed_at'), 'client_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_client_history_client_id'), 'client_history', ['client_id'], unique=False)
    op.drop_index('name', table_name='clients')
    op.create_index(op.f('ix_clients_relation_type'), 'clients', ['relation_type'], unique=False)
    op.create_index(op.f('ix_clients_status'), 'clients', ['status'], unique=False)
    op.create_index('uk_clients_name', 'clients', ['name'], unique=True)
    op.create_index(op.f('ix_groups_client_id'), 'groups', ['client_id'], unique=False)
    op.alter_column('project_history', 'changed_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_project_history_action'), 'project_history', ['action'], unique=False)
    op.create_index(op.f('ix_project_history_changed_at'), 'project_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_project_history_project_id'), 'project_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('ix_projects_group_id'), 'projects', ['group_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_sow_history_sow_id'), 'sow_history', ['sow_id'], unique=False)
    op.create_index(op.f('ix_sow_history_version_number'), 'sow_history', ['version_number'], unique=False)
    op.alter_column('sow_roles', 'role_name',
               existing_type=mysql.ENUM('Backend Developer', 'Frontend Developer', 'Designer', 'Tester', 'Business Analyst', 'Architect', 'Project Manager'),
               type_=sa.Enum('BACKEND_DEVELOPER', 'FRONTEND_DEVELOPER', 'DESIGNER', 'TESTER', 'BUSINESS_ANALYST', 'ARCHITECT', 'PROJECT_MANAGER', name='sowrolename'),
               existing_nullable=False)
    op.create_index(op.f('ix_sow_roles_sow_id'), 'sow_roles', ['sow_id'], unique=False)
    op.drop_constraint('sow_roles_ibfk_1', 'sow_roles', type_='foreignkey')
    op.create_foreign_key(None, 'sow_roles', 'sows', ['sow_id'], ['id'])
    op.create_index(op.f('ix_sows_client_id'), 'sows', ['client_id'], unique=False)
    op.create_index(op.f('ix_sows_status'), 'sows', ['status'], unique=False)
    op.alter_column('user_sessions', 'last_accessed',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.drop_constraint('user_sessions_ibfk_1', 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'])
    op.drop_column('user_sessions', 'id')
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('hire_date', sa.DateTime(), nullable=True))
    op.drop_index('email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_column('users', 'hire_date')
    op.drop_column('users', 'department')
    op.drop_column('users', 'phone')
    op.add_column('user_sessions', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key('user_sessions_ibfk_1', 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.alter_column('user_sessions', 'last_accessed',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_sows_status'), table_name='sows')
    op.drop_index(op.f('ix_sows_client_id'), table_name='sows')
    op.drop_constraint(None, 'sow_roles', type_='foreignkey')
    op.create_foreign_key('sow_roles_ibfk_1', 'sow_roles', 'sows', ['sow_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sow_roles_sow_id'), table_name='sow_roles')
    op.alter_column('sow_roles', 'role_name',
               existing_type=sa.Enum('BACKEND_DEVELOPER', 'FRONTEND_DEVELOPER', 'DESIGNER', 'TESTER', 'BUSINESS_ANALYST', 'ARCHITECT', 'PROJECT_MANAGER', name='sowrolename'),
               type_=mysql.ENUM('Backend Developer', 'Frontend Developer', 'Designer', 'Tester', 'Business Analyst', 'Architect', 'Project Manager'),
               existing_nullable=False)
    op.drop_index(op.f('ix_sow_history_version_number'), table_name='sow_history')
    op.drop_index(op.f('ix_sow_history_sow_id'), table_name='sow_history')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_group_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_index(op.f('ix_project_history_project_id'), table_name='project_history')
    op.drop_index(op.f('ix_project_history_changed_at'), table_name='project_history')
    op.drop_index(op.f('ix_project_history_action'), table_name='project_history')
    op.alter_column('project_history', 'changed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_groups_client_id'), table_name='groups')
    op.drop_index('uk_clients_name', table_name='clients')
    op.drop_index(op.f('ix_clients_status'), table_name='clients')
    op.drop_index(op.f('ix_clients_relation_type'), table_name='clients')
    op.create_index('name', 'clients', ['name'], unique=True)
    op.drop_index(op.f('ix_client_history_client_id'), table_name='client_history')
    op.drop_index(op.f('ix_client_history_changed_at'), table_name='client_history')
    op.drop_index(op.f('ix_client_history_action'), table_name='client_history')
    op.alter_column('client_history', 'changed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_constraint(None, 'client_contacts', type_='foreignkey')
    op.create_foreign_key('client_contacts_ibfk_1', 'client_contacts', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_client_contacts_email'), table_name='client_contacts')
    op.drop_index(op.f('ix_client_contacts_client_id'), table_name='client_contacts')
    op.drop_index(op.f('ix_assignments_user_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_project_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignment_history_changed_at'), table_name='assignment_history')
    op.drop_index(op.f('ix_assignment_history_assignment_id'), table_name='assignment_history')
    op.drop_index(op.f('ix_assignment_history_action'), table_name='assignment_history')
    op.alter_column('assignment_history', 'changed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.create_table('health_check',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), server_default=sa.text("'healthy'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
